a.out : client-sdl.cpp config.hpp game.hpp utils.hpp
	g++ client-sdl.cpp -std=c++11 -lSDL2main -lSDL2 -lSDL2_mixer -pthread -o a.out
debug :
	g++ client-sdl.cpp -std=c++11 -lSDL2main -lSDL2 -lSDL2_mixer -ggdb -pthread -o a.out
